package manual

import "fmt"

func StorageUsage() {

	fmt.Println("path=")
	fmt.Println("unit-len=")
	fmt.Println("threads=")
	fmt.Println("indexes=key,etag,fsize")
	fmt.Println()
	fmt.Println("参数值     含义")
	fmt.Println("path      选择从[云存储空间列举]还是从[本地路径文件中读取]资源，本地数据源时填写本地文件或者目录路径，云存储数据源时可填写 \"qiniu://<bucket>\"、\"tencent://<bucket>\" 等")
	fmt.Println("unit-len  表示一次读取的文件个数（读取或列举长度，不同数据源有不同默认值），对应与读取文件时每次处理的行数或者列举请求时设置的 limit 参数")
	fmt.Println("threads   表示预期最大线程数，若实际得到的文件数或列举前缀数小于该值时以实际数目为准")
	fmt.Println("indexes   资源元信息字段索引（下标），设置输入行对应的元信息字段下标")

	fmt.Println()
	fmt.Println("<密钥配置>")
	fmt.Println("region=")
	fmt.Println("bucket=")
	fmt.Println("marker=")
	fmt.Println("start=")
	fmt.Println("end=")
	fmt.Println("prefixes=")
	fmt.Println("anti-prefixes=")
	fmt.Println("prefix-left=")
	fmt.Println("prefix-right=")
	fmt.Println()
	fmt.Println("参数名             含义")
	fmt.Println("<密钥配置>       密钥对字符串")
	fmt.Println("region          存储区域")
	fmt.Println("bucket          需要列举的空间名称，通过 \"path=qiniu://\" 来设置的话此参数可不设置，设置则会覆盖 path 中指定的 bucket 值")
	fmt.Println("prefixes        表示只列举某些文件名前缀的资源，，支持以 , 分隔的列表，如果前缀本身包含 ,\\= 等特殊字符则需要加转义符，如 \\,")
	fmt.Println("prefix-config   该选项用于设置列举前缀的配置文件路径，配置文件格式为 json，参考 prefix-config 配置文件")
	fmt.Println("anti-prefixes   表示列举时排除某些文件名前缀的资源，支持以 , 分隔的列表，特殊字符同样需要转义符")
	fmt.Println("prefix-left     当设置多个前缀时，可选择是否列举所有前缀 ASCII 顺序之前的文件")
	fmt.Println("prefix-right    当设置多个前缀时，可选择是否列举所有前缀 ASCII 顺序之后的文件")
	fmt.Println()
	fmt.Println("支持从不同的云存储上列举出空间文件，默认线程数(threads 参数)为 50，千万以内文件数量可以不增加线程，建议阅读并发列举参考参数设置优化列举效率，通常云存储空间列举的必须参数包括密钥（可通过 account 方式来使用，下述为了直接表示密钥参数名所以没有体现 account 用法）、空间名（通过 path 或 bucket 设置）及空间所在区域(通过 region 设置，允许不设置的情况下表明支持自动查询)。")
	fmt.Println()
	fmt.Println("各存储数据源配置参数：")
	fmt.Println("storage 源   密钥和 region 字段                                     对应关系和描述")
	fmt.Println("qiniu:      ak= sk= region=z0/z1/z2/...                     密钥对为七牛云账号的 AccessKey 和 SecretKey，region使用简称(可不设置)，参考七牛 Region https://developer.qiniu.com/kodo/manual/1671/region-endpoint")
	fmt.Println("tencent:    ten-id= ten-secret= region=ap-beijing/...       密钥对为腾讯云账号的 SecretId 和 SecretKey，region使用简称(可不设置)，参考腾讯 Region https://cloud.tencent.com/document/product/436/6224")
	fmt.Println("aliyun      ali-id= ali-secret= region=oss-cn-hangzhou/...  密钥对为阿里云账号的 AccessKeyId 和 AccessKeySecret，region使用简称(可不设置)，参考阿里 Region https://help.aliyun.com/document_detail/31837.html")
	fmt.Println("aws/s3      s3-id= s3-secret= region=ap-east-1/...          密钥对为 aws/s3 api 账号的 AccessKeyId 和 SecretKey，region使用简称(可不设置)，参考AWS Region https://docs.aws.amazon.com/zh_cn/general/latest/gr/rande.html")
	fmt.Println("upyun       up-id= up-secret=                               密钥对为又拍云存储空间授权的操作员和其密码，又拍云存储目前没有 region 概念")
	fmt.Println("huawei      hua-id= hua-secret= region=cn-north-1/...       密钥对为华为云账号的 AccessKeyId 和 SecretAccessKey，region(可不设置)使用简称，参考华为 Region https://support.huaweicloud.com/devg-obs/zh-cn_topic_0105713153.html")
	fmt.Println("baidu       bai-id= bai-secret= region=bj/gz/su...          密钥对为百度云账号的 AccessKeyId 和 SecretAccessKey，region(可不设置)使用简称，参考百度 Region https://cloud.baidu.com/doc/BOS/s/Ojwvyrpgd/")
}
